version: '3.2'

services:
  stub:
    build:
      context: ./
      dockerfile: Dockerfile.stub
    ports:
      - 8080:8080

  api:
    build:
      context: ./../
      dockerfile: docker/Dockerfile
    env_file: .env
    links:
      - stub
    depends_on:
      - stub
    ports:
      - 8081:8081